<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.trionesdev.boot</groupId>
    <artifactId>triones-spring-boot-starters</artifactId>
    <packaging>pom</packaging>
    <version>3.0-SNAPSHOT</version>
    <name>Triones:Boot</name>
    <modules>
        <module>triones-spring-boot-starter</module>
        <module>triones-mybatis-plus-spring-boot-starter</module>
        <module>triones-security-spring-boot-starter</module>
        <module>triones-openfeign-spring-boot-starter</module>
        <module>triones-opentelemetry-spring-boot-starter</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <spring-boot.version>3.3.0</spring-boot.version>
        <spring-cloud.veriosn>2023.0.1</spring-cloud.veriosn>
        <mybatis-plus-boot.version>3.5.6</mybatis-plus-boot.version>
        <triones-spring-commons.version>3.0-SNAPSHOT</triones-spring-commons.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
                <optional>true</optional>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.veriosn}</version>
                <type>pom</type>
                <scope>import</scope>
                <optional>true</optional>
            </dependency>
            <dependency>
                <groupId>com.trionesdev.commons</groupId>
                <artifactId>triones-spring-commons</artifactId>
                <version>${triones-spring-commons.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.trionesdev.opentelemetry</groupId>
                <artifactId>triones-opentelemetry-spring-boot-starters</artifactId>
                <version>1.0-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus-boot.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.jsqlparser</groupId>
                <artifactId>jsqlparser</artifactId>
                <version>4.9</version>
            </dependency>
            <dependency>
                <groupId>org.mybatis</groupId>
                <artifactId>mybatis-spring</artifactId>
                <version>3.0.3</version>
            </dependency>
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-core</artifactId>
                <version>5.8.27</version>
            </dependency>
            <!-- moensun-boot-starter-->

            <dependency>
                <groupId>com.trionesdev.boot</groupId>
                <artifactId>triones-spring-boot-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.trionesdev.boot</groupId>
                <artifactId>triones-security-spring-boot-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.trionesdev.boot</groupId>
                <artifactId>triones-openfeign-spring-boot-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.trionesdev.boot</groupId>
                <artifactId>triones-mybatis-plus-spring-boot-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.trionesdev.boot</groupId>
                <artifactId>triones-opentelemetry-spring-boot-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!--moensun-boot-starter-->
        </dependencies>
    </dependencyManagement>

    <distributionManagement>
        <!--        <snapshotRepository>
                    <id>ossrh</id>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                </snapshotRepository>
                <repository>
                    <id>ossrh</id>
                    <url>https://oss.sonatype.org/service/local/staging/deploy/maven2</url>
                </repository>-->
        <snapshotRepository>
            <id>moensun</id>
            <url>https://nexus.moensun.com/repository/maven-snapshots/</url>
        </snapshotRepository>
        <repository>
            <id>moensun</id>
            <url>https://nexus.moensun.com/repository/maven-releases/</url>
        </repository>
    </distributionManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.16.2</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>3.0.1</version>
                <configuration>
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                    <useReleaseProfile>false</useReleaseProfile>
                    <releaseProfiles>release</releaseProfiles>
                    <goals>deploy</goals>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>ms-repository</id>
            <url>https://nexus.moensun.com/repository/maven-public/</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>daily</updatePolicy>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>ms-repository</id>
            <url>https://nexus.moensun.com/repository/maven-public/</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>daily</updatePolicy>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>

</project>