<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.trionesdev.springboot</groupId>
    <artifactId>triones-spring-boot-dependencies</artifactId>
    <version>3.0.0-SNAPSHOT</version>
    <name>Triones:SpringBoot:Dependencies</name>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-boot.version>3.3.0</spring-boot.version>
        <spring-cloud.veriosn>2023.0.1</spring-cloud.veriosn>
        <mybatis-plus-boot.version>3.5.6</mybatis-plus-boot.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.trionesdev.commons</groupId>
                <artifactId>triones-spring-commons-dependencies</artifactId>
                <version>3.0.0-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
                <optional>true</optional>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.veriosn}</version>
                <type>pom</type>
                <scope>import</scope>
                <optional>true</optional>
            </dependency>
            <dependency>
                <groupId>com.trionesdev.opentelemetry</groupId>
                <artifactId>triones-opentelemetry-spring-boot-starters</artifactId>
                <version>1.0-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus-boot.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.jsqlparser</groupId>
                <artifactId>jsqlparser</artifactId>
                <version>4.9</version>
            </dependency>
            <dependency>
                <groupId>org.mybatis</groupId>
                <artifactId>mybatis-spring</artifactId>
                <version>3.0.3</version>
            </dependency>
            <!-- moensun-boot-starter-->

            <dependency>
                <groupId>com.trionesdev.springboot</groupId>
                <artifactId>triones-spring-boot-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.trionesdev.springboot</groupId>
                <artifactId>triones-security-spring-boot-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.trionesdev.springboot</groupId>
                <artifactId>triones-openfeign-spring-boot-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.trionesdev.springboot</groupId>
                <artifactId>triones-mybatis-plus-spring-boot-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.trionesdev.springboot</groupId>
                <artifactId>triones-opentelemetry-spring-boot-starter</artifactId>
                <version>${project.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <profiles>
        <profile>
            <id>moensun</id>
            <distributionManagement>
                <snapshotRepository>
                    <id>moensun</id>
                    <url>https://nexus.moensun.com/repository/maven-snapshots/</url>
                </snapshotRepository>
                <repository>
                    <id>moensun</id>
                    <url>https://nexus.moensun.com/repository/maven-releases/</url>
                </repository>
            </distributionManagement>
        </profile>
    </profiles>
</project>